Allow optionally specifying Series Instance UID
Specifying the series ID means that only dicoms matching that value will
be discovered and returned as the image.

Previously , discovering images would sometimes fail in
dcminputadapter.py if dicoms in the folder did not have the same ID
value. This is due to GetGDCMSeriesFileNames from SimpleITK returning
 only the file names associated with the first discovered series id.
Thus (for instance) only an RD file would be discovered and returned
 as the dicom image.

This would then break the structure import in rtstructcontour2mask.py on
this line:
world_coords = dicom_image.TransformPhysicalPointToContinuousIndex((coordinates['x'][index], coordinates['y'][index], coordinates['z'][index]))
with the error
Traceback (most recent call last):
  File "dcm_to_numpy.py", line 78, in dcm_to_nifti
    dcmrtstruct2nii(rtstruct_path,
  File "...\dcmrtstruct2nii\dcmrtstruct2nii\facade\dcmrtstruct2nii.py", line 79, in dcmrtstruct2nii
    mask = dcm_patient_coords_to_mask.convert(rtstruct['sequence'], dicom_image, mask_background_value, mask_foreground_value)
  File "...\dcmrtstruct2nii\dcmrtstruct2nii\adapters\convert\rtstructcontour2mask.py", line 39, in convert
    world_coords = dicom_image.TransformPhysicalPointToContinuousIndex((coordinates['x'][index], coordinates['y'][index], coordinates['z'][index]))
  File "C:\Users\sgay1\Miniconda3\envs\tf2.3\lib\site-packages\SimpleITK\SimpleITK.py", line 3253, in TransformPhysicalPointToContinuousIndex
    return _SimpleITK.Image_TransformPhysicalPointToContinuousIndex(self, point)
RuntimeError: Exception thrown in SimpleITK Image_TransformPhysicalPointToContinuousIndex: d:\bld\libsimpleitk_1627514864077\work\code\common\src\sitkPimpleImageBase.hxx:237:
sitk::ERROR: vector dimension mismatch